Добавлены web-страницы и стили
foz-x60008d/TicketSystem pull request #1
Opened 2020-04-05 07:12 UTC by SergCha

2020-04-06 17:04 UTC, avkorablev requested changes
Удаляй файлы с js и css фреймворка - подключаешь это через CDN, тут они не нужны.
Удаляй все фалы, которые относятся к шаблонам но лежат не в папке support/tickets/static
Удали все лишние картинки
support/tickets/templates/tickets/LICENSE - удалить
support/tickets/templates/tickets/README.md  - удалить
исключи папку support/virtualenv из репозитория

2020-04-07 07:15 UTC, avkorablev requested changes

2020-04-07 07:15 UTC, avkorablev commented on support/tickets/templates/tickets/check.html
> +  <link rel="stylesheet" href="css/style.css">
css/style.css -> /static/css/style.css

2020-04-07 07:15 UTC, avkorablev commented on support/tickets/templates/tickets/check.html
> +<script src="js/materialize.js"></script>
надо подключить это через cdn, если можно

2020-04-07 07:15 UTC, avkorablev commented on support/tickets/templates/tickets/check.html
> +<script src="js/init.js"></script>
И это

2020-04-07 07:15 UTC, avkorablev commented on support/tickets/templates/tickets/check.html
> +</html>
пустая строка в конце файлов - это общепринятое правило

2020-04-07 07:15 UTC, avkorablev commented on support/tickets/templates/tickets/css/style.css
> +nav	{
удали этот файл

2020-04-07 13:15 UTC, avkorablev requested changes

2020-04-07 13:15 UTC, avkorablev commented on support/tickets/templates/tickets/check.html
> +<head>
Весь блок head нужно вынести в отдельный шаблон: support/tickets/templates/tickets/parts/head.html

Здесь весь блок заменить на `{% include "parts/head.html" %}`

2020-04-07 13:15 UTC, avkorablev commented on support/tickets/templates/tickets/check.html
> +  <div class="navbar-fixed">
Весь блок `div class="navbar-fixed"` нужно вынести в отдельный шаблон: support/tickets/templates/tickets/parts/navbar.html

Здесь весь блок заменить на {% include "parts/navbar.html" %}

2020-04-07 13:15 UTC, avkorablev commented on support/tickets/templates/tickets/check.html
> +<!-- FOOTER-->
Весь блок footer вместе со скриптами нужно вынести в отдельный шаблон: support/tickets/templates/tickets/parts/footer.html

Здесь весь блок заменить на {% include "parts/footer.html" %}

2020-04-07 13:15 UTC, avkorablev commented on support/tickets/urls.py
> +    path('', views.check, name='check'),
пути должны быть разными

2020-04-08 11:10 UTC, avkorablev requested changes
Удали:
support/tickets/static/css/materialize.css
support/tickets/static/css/materialize.min.css
support/tickets/templates/tickets/css/materialize.css
support/tickets/templates/tickets/css/materialize.min.css

Сделай копию support/tickets/templates/tickets/check.html и назови ее base.html

2020-04-08 11:10 UTC, avkorablev commented on support/tickets/templates/tickets/parts/footer.html
> +  <div class="container">
Этот блок зачем?

2020-04-08 11:10 UTC, avkorablev commented on support/tickets/templates/tickets/parts/footer.html
> +      <a class="purple-text text-darken-3" href="http://materializecss.com">Ticket System</a>
Эта ссылка зачем?

2020-04-08 11:10 UTC, avkorablev commented on support/tickets/templates/tickets/parts/footer.html
> +<script src="js/materialize.js"></script>
Ссылка на cdn

2020-04-08 11:10 UTC, avkorablev commented on support/tickets/templates/tickets/parts/footer.html
> +<script src="js/init.js"></script>
Ссылка на cdn и пустая строка в файле

2020-04-08 11:10 UTC, avkorablev commented on support/tickets/templates/tickets/parts/head.html
> +  <title>Статус обращения</title>
внутри title нужно вставить `{% block title %}{% endblock %}`

2020-04-08 11:10 UTC, avkorablev commented on support/tickets/templates/tickets/parts/head.html
> +  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
пустая строка в конце файла

2020-04-08 11:10 UTC, avkorablev commented on support/tickets/templates/tickets/parts/navbar.html
> +          <a href ="home.html" class="brand-logo">Ticket System</a>
странное форматирование: пробел между href и равно лишний

ссылки лучше делать так (внутри href прописывать): `{% url 'home' %}`

2020-04-08 11:10 UTC, avkorablev commented on support/tickets/urls.py
> +    path('', views.home, name='home'),
так работать не будет. они должны быть внутри urlpatterns

2020-04-08 11:10 UTC, avkorablev commented on support/tickets/urls.py
> +    path('', views.check, name='check'),
два одинаковых пути - это плохо

2020-04-08 11:10 UTC, avkorablev commented on support/tickets/templates/tickets/parts/navbar.html
> +  <div class="section no-pad-bot" id="index-banner">
Это же уже не навигация?

2020-04-08 13:15 UTC, SergCha commented on support/tickets/templates/tickets/parts/navbar.html
> +          <a href ="home.html" class="brand-logo">Ticket System</a>
Я так понимаю форматирование д.б. таким: <a href="{% url 'home' %}" ....

2020-04-08 13:22 UTC, avkorablev commented on support/tickets/templates/tickets/parts/navbar.html
> +          <a href ="home.html" class="brand-logo">Ticket System</a>
да

2020-04-08 16:18 UTC, SergCha commented
По ссылкам открывается всё время стартовая страница.

2020-04-10 13:26 UTC, merged