Запись в базу данных
foz-x60008d/TicketSystem pull request #2
Opened 2020-04-16 14:06 UTC by SergCha

Не получается записывать данные формы в базу данных, полю state надо присваивать значения автоматически.

2020-04-16 15:57 UTC, avkorablev reviewed
Это что? support/create

2020-04-16 16:05 UTC, avkorablev reviewed
Удаляй support/virtualenv - невозможно же посмотреть PR. Этот вообще не должно попадать в коммит. Смотри какие файлы в коммит добавляешь. Для этого есть git status. А еще лучше пользуйся PyCharm с нормальным встроенным git-клиентом

2020-04-16 16:05 UTC, avkorablev commented on support/support/settings.py
> +STATIC_ROOT = os.path.join(BASE_DIR, 'static')
Пустая строка в конце файла

2020-04-16 16:05 UTC, avkorablev commented on support/tickets/models.py
> +from django.conf import settings
Зачем эта строка?

2020-04-16 16:05 UTC, avkorablev commented on support/tickets/templates/home.html
> +			<div style="float: right;">
А зачем две кнопки?

2020-04-16 16:05 UTC, avkorablev commented on support/tickets/templates/login.php
> +<form method="POST">
Это за чем?

2020-04-16 16:05 UTC, avkorablev commented on support/tickets/urls.py
> +    path('check/login.php', views.login, name='login'),
Зачем? причем тут php?

2020-04-21 17:27 UTC, avkorablev requested changes

2020-04-21 17:27 UTC, avkorablev commented on support/tickets/forms.py
> +        reporter_email = forms.EmailField()
Слишком много пробелов. На 4 штуки меньше, пожалуйста

2020-04-21 17:27 UTC, avkorablev commented on support/tickets/urls.py
> +    path('check/search/', views.search_ticket),
Этой строки быть не должно. Достаточно 9-ой

2020-04-21 17:27 UTC, avkorablev commented on support/tickets/views.py
> +        ticket_id = request.POST.get('id_ticket')
Не хватает:
search_ticket_form = SearchTicketForm(request.POST)
if ticket_form.is_valid():
И данные брать из проверенной формы

2020-04-21 17:27 UTC, avkorablev commented on support/tickets/views.py
> +        search_ticket_form = get_object_or_404(Ticket, uuid=ticket_id, reporter_email=ticket_email)
это уже не форма, это ticket. Для него лучше return render(request, 'tickets/detail.html', {'ticket': ticket})

2020-04-21 17:27 UTC, avkorablev commented on support/tickets/views.py
> +    return render(request, "search.html", {'form' : search_ticket_form})
А вот здесь check.html

2020-04-21 17:27 UTC, avkorablev commented on support/tickets/views.py
> +        search_ticket_form = get_object_or_404(Ticket, uuid=ticket_id, reporter_email=ticket_email)
Шаблон только соответствующий подставь

2020-04-21 17:27 UTC, avkorablev commented on support/tickets/templates/check.html
> +        <form method="POST" id="id_ticket" action="search/">{% csrf_token %}
в action так же, как и остальных шаблонах url по имени, а не "хардкод"

2020-04-21 17:28 UTC, avkorablev requested changes

2020-04-21 17:28 UTC, avkorablev commented on support/tickets/views.py
> +def search_ticket(request):
Это назови check, а предыдущую убей

2020-04-22 03:26 UTC, SergCha commented on support/tickets/urls.py
> +    path('check/search/', views.search_ticket),
какой этой, этой: path('check/search/', views.search_ticket),?

2020-04-22 03:29 UTC, SergCha commented on support/tickets/views.py
> +        ticket_id = request.POST.get('id_ticket')
а при чем тут ticket_form если форма, которая работает search_ticket_form?

2020-04-22 03:33 UTC, SergCha commented on support/tickets/views.py
> +def search_ticket(request):
что check назвать, search_ticket? но у нас уже есть такая вьюха.

2020-04-22 03:35 UTC, SergCha commented on support/tickets/templates/check.html
> +        <form method="POST" id="id_ticket" action="search/">{% csrf_token %}
у нас во всех шаблонах action прописан именно так

2020-04-22 05:26 UTC, avkorablev commented on support/tickets/urls.py
> +    path('check/search/', views.search_ticket),
именно

2020-04-22 05:27 UTC, avkorablev commented on support/tickets/views.py
> +        ticket_id = request.POST.get('id_ticket')
не аккуратный пример. там, конечно, if search_ticket_form.is_valid():

2020-04-22 05:27 UTC, avkorablev commented on support/tickets/templates/check.html
> +        <form method="POST" id="id_ticket" action="search/">{% csrf_token %}
значит везде надо поменять

2020-04-22 05:28 UTC, avkorablev commented on support/tickets/views.py
> +def search_ticket(request):
я и говорю, эта должна называться check, а ту которая есть нужно удалить

2020-04-22 05:38 UTC, SergCha commented on support/tickets/views.py
> +        ticket_id = request.POST.get('id_ticket')
так бы и написал, что добавь валидацию)))

2020-04-22 05:39 UTC, SergCha commented on support/tickets/views.py
> +        search_ticket_form = get_object_or_404(Ticket, uuid=ticket_id, reporter_email=ticket_email)
а чем search.html не устраивает?

2020-04-22 05:40 UTC, SergCha commented on support/tickets/views.py
> +    return render(request, "search.html", {'form' : search_ticket_form})
где? вместо "search.html"?

2020-04-22 07:07 UTC, closed without merging